-- Cron jobs pour scrape-soirees multi-villes
-- Reparties entre 3h00 et 3h30 UTC

SELECT cron.schedule('scrape-soirees-lyon', '0 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lyon"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-marseille', '3 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Marseille"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-bordeaux', '6 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Bordeaux"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-lille', '9 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lille"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-nantes', '12 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nantes"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-strasbourg', '15 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Strasbourg"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-nice', '18 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nice"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-montpellier', '21 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Montpellier"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-rennes', '24 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Rennes"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-grenoble', '27 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Grenoble"}'::jsonb);$$);
SELECT cron.schedule('scrape-soirees-toulouse-eb', '30 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-soirees',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Toulouse"}'::jsonb);$$);
