-- Cron weekend-picks : jeudi a 12h UTC, une ville toutes les 2 min

SELECT cron.schedule('weekend-picks-paris', '0 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Paris"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-lyon', '2 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lyon"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-marseille', '4 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Marseille"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-bordeaux', '6 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Bordeaux"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-lille', '8 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lille"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-nantes', '10 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nantes"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-toulouse', '12 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Toulouse"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-strasbourg', '14 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Strasbourg"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-nice', '16 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nice"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-montpellier', '18 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Montpellier"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-rennes', '20 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Rennes"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-geneve', '22 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Geneve"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-grenoble', '24 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Grenoble"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-dijon', '26 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Dijon"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-angers', '28 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Angers"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-toulon', '30 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Toulon"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-saint-etienne', '32 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Saint-Etienne"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-rouen', '34 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Rouen"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-metz', '36 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Metz"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-nancy', '38 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nancy"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-avignon', '40 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Avignon"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-brest', '42 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Brest"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-nimes', '44 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nimes"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-bayonne', '46 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Bayonne"}'::jsonb);$$);
SELECT cron.schedule('weekend-picks-carcassonne', '48 12 * * 4', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/weekend-picks',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Carcassonne"}'::jsonb);$$);
