-- Cron jobs pour scrape-food multi-villes
-- Reparties entre 1h30 et 1h55 UTC

SELECT cron.schedule('scrape-food-paris', '30 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Paris"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-lyon', '32 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lyon"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-marseille', '34 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Marseille"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-bordeaux', '36 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Bordeaux"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-lille', '38 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lille"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-nantes', '40 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nantes"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-toulouse', '42 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Toulouse"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-nice', '44 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nice"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-strasbourg', '46 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Strasbourg"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-rennes', '48 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Rennes"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-montpellier', '50 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Montpellier"}'::jsonb);$$);
SELECT cron.schedule('scrape-food-grenoble', '52 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-food',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Grenoble"}'::jsonb);$$);
