-- Table unifiée pour tous les lieux "En Famille"
CREATE TABLE IF NOT EXISTS public.family_venues (
  id SERIAL PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,       -- 'Parc d''attractions', 'Aire de jeux', 'Cinema', etc.
  groupe TEXT DEFAULT '',       -- sous-groupe pour affichage (ex: 'Multiplexes & grands cinemas')
  description TEXT DEFAULT '',
  adresse TEXT DEFAULT '',
  ville TEXT DEFAULT 'Toulouse',
  horaires TEXT DEFAULT '',
  tarif TEXT DEFAULT '',
  telephone TEXT DEFAULT '',
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  website_url TEXT DEFAULT '',
  ticket_url TEXT DEFAULT '',
  lien_maps TEXT DEFAULT '',
  photo TEXT DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.family_venues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon read family_venues" ON public.family_venues FOR SELECT USING (true);

-- ═══════════════════════════════════════════════════════
-- Parc d'attractions (9)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, description, adresse, ville, horaires, telephone, latitude, longitude, website_url, lien_maps) VALUES
('animaparc', 'Animaparc', 'Parc d''attractions', '', 'Lieu-dit En Jacca, 31530 Levignac', 'Levignac', 'Mer-Dim 10h-18h (saison)', '05 62 79 54 54', 43.6445, 1.1945, 'https://www.animaparc.com/', 'https://maps.google.com/?q=Animaparc+Levignac'),
('walibi_sud_ouest', 'Walibi Sud-Ouest', 'Parc d''attractions', '', 'Chateau de Caudouin, 47310 Roquefort', 'Roquefort', 'Saison avr-oct, 10h-18h', '05 53 96 58 32', 44.0400, 0.3475, 'https://www.walibi.com/sud-ouest', 'https://maps.google.com/?q=Walibi+Sud-Ouest+Roquefort'),
('rigolus_park', 'Rigolus Park', 'Parc d''attractions', '', '11 Rue du Stade, 31240 L''Union', 'L''Union', 'Mer-Dim 10h-19h', '05 61 74 45 80', 43.6555, 1.4870, 'https://www.rigoluspark.fr/', 'https://maps.google.com/?q=Rigolus+Park+L+Union'),
('smash_club', 'Smash Club', 'Parc d''attractions', '', '4 Chemin de Bordeblanque, 31240 L''Union', 'L''Union', 'Mar-Dim 10h-22h', '05 61 09 92 39', 43.6540, 1.4900, 'https://www.smash-club.fr/', 'https://maps.google.com/?q=Smash+Club+L+Union'),
('playpark', 'Playpark', 'Parc d''attractions', '', 'Zone Commerciale, 31120 Portet-sur-Garonne', 'Portet-sur-Garonne', 'Lun-Dim 10h-19h', '05 34 47 92 00', 43.5225, 1.4000, 'https://www.playpark.fr/', 'https://maps.google.com/?q=Playpark+Portet-sur-Garonne'),
('pop_corn_labyrinthe', 'Pop Corn Labyrinthe Castelmaurou', 'Parc d''attractions', '', 'Route de Lapeyrouse, 31180 Castelmaurou', 'Castelmaurou', 'Juil-Sept, 10h-19h', '06 07 10 63 85', 43.6750, 1.5255, 'https://www.popcornlabyrinthe.com/', 'https://maps.google.com/?q=Pop+Corn+Labyrinthe+Castelmaurou'),
('tepacap', 'Tepacap', 'Parc d''attractions', '', 'Lieu-dit Bouconne, 31370 Rieumes', 'Rieumes', 'Mer-Dim 10h-18h (saison)', '05 61 91 98 90', 43.4110, 1.1195, 'https://www.tepacap.fr/', 'https://maps.google.com/?q=Tepacap+Rieumes'),
('lac_thoux', 'Base de Loisirs Lac de Thoux-St-Cricq', 'Parc d''attractions', '', 'Lac de Thoux-Saint-Cricq, 32430 Thoux', 'Thoux', 'Juil-Aout 10h-19h', '05 62 65 71 12', 43.5285, 0.9580, 'https://www.lacthoux.com/', 'https://maps.google.com/?q=Lac+de+Thoux-Saint-Cricq'),
('parc_saint_sardos', 'Parc de Loisirs de Saint-Sardos', 'Parc d''attractions', '', 'Lac de Saint-Sardos, 82600 Saint-Sardos', 'Saint-Sardos', 'Juil-Aout 10h-19h', '05 63 02 61 00', 43.9740, 1.1310, 'https://www.tourisme-castelsarrasin-moissac.fr/', 'https://maps.google.com/?q=Lac+de+Saint-Sardos');

-- ═══════════════════════════════════════════════════════
-- Aire de jeux (10)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, description, adresse, horaires, latitude, longitude, website_url, lien_maps) VALUES
('jardin_royal', 'Jardin Royal', 'Aire de jeux', 'Grande aire de jeux centrale, ideale pour petits et grands a proximite du centre.', 'Rue du Jardin Royal, 31000 Toulouse', 'Tous les jours 7h30-21h (ete), 7h30-18h30 (hiver)', 43.6020, 1.4510, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Jardin+Royal+Toulouse'),
('jardin_japonais', 'Jardin Japonais', 'Aire de jeux', 'Ambiance zen + petits jeux pour enfants, tres agreable.', 'Jardin Japonais, 31400 Toulouse', 'Tous les jours 7h45-20h (ete), 7h45-17h30 (hiver)', 43.5895, 1.4430, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Jardin+Japonais+Toulouse'),
('parc_maourine', 'Parc de la Maourine', 'Aire de jeux', 'Espaces verts + structures de jeux et zones ombragees.', 'Chemin de la Maourine, 31200 Toulouse', 'Tous les jours 7h30-21h (ete), 7h30-18h (hiver)', 43.6340, 1.4250, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Parc+de+la+Maourine+Toulouse'),
('parc_reynerie', 'Parc de la Reynerie', 'Aire de jeux', 'Grand parc avec aires de jeux, lac et pistes cyclables.', 'Chemin de Reynerie, 31100 Toulouse', 'Tous les jours 7h30-21h (ete), 7h30-18h (hiver)', 43.5760, 1.3920, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Parc+de+la+Reynerie+Toulouse'),
('parc_ramier', 'Parc du Ramier', 'Aire de jeux', 'Vaste parc au bord de la Garonne + aires de jeux et espaces pique-nique.', 'Ile du Ramier, 31400 Toulouse', 'Tous les jours, acces libre', 43.5850, 1.4380, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Parc+du+Ramier+Toulouse'),
('parc_grand_rond', 'Parc Grand Rond', 'Aire de jeux', 'Beaux jardins + aire de jeux pour enfants, idealement situe.', 'Grand Rond, 31400 Toulouse', 'Tous les jours 7h30-21h (ete), 7h30-18h30 (hiver)', 43.5940, 1.4520, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Grand+Rond+Toulouse'),
('parc_poudrerie', 'Parc de la Poudrerie', 'Aire de jeux', 'Espace plus naturel, zones d''exploration et jeux libres.', 'Chemin de la Poudrerie, 31200 Toulouse', 'Tous les jours 7h30-20h (ete), 7h30-17h30 (hiver)', 43.6380, 1.4580, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Parc+de+la+Poudrerie+Toulouse'),
('parc_paleficat', 'Parc de Paleficat', 'Aire de jeux', 'Aire de jeux enfants + bancs pour parents.', 'Chemin de Paleficat, 31500 Toulouse', 'Tous les jours, acces libre', 43.6400, 1.4900, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Parc+de+Paleficat+Toulouse'),
('jardin_raymond_vi', 'Jardin Raymond VI', 'Aire de jeux', 'Espace petit parc avec structure de jeux.', 'Allee Charles de Fitte, 31300 Toulouse', 'Tous les jours, acces libre', 43.6070, 1.4310, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Jardin+Raymond+VI+Toulouse'),
('parc_francois_verdier', 'Parc Francois Verdier', 'Aire de jeux', 'Espaces verts et petite aire de jeux enfants.', 'Place Francois Verdier, 31000 Toulouse', 'Tous les jours, acces libre', 43.6005, 1.4540, 'https://www.toulouse.fr/web/environnement/parcs-et-jardins', 'https://maps.google.com/?q=Place+Francois+Verdier+Toulouse');

-- ═══════════════════════════════════════════════════════
-- Parc animalier (6)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, groupe, description, adresse, horaires, telephone, latitude, longitude, website_url, ticket_url, lien_maps) VALUES
('african_safari', 'African Safari - Zoo de Plaisance du Touch', 'Parc animalier', 'Zoo & safari', 'Grand parc animalier avec plus de 600 animaux de 80 especes. Safari en voiture ou visite a pied.', 'Chemin du Bois de la Lande, 31830 Plaisance-du-Touch', 'Tous les jours 10h-18h (saison)', '05 61 86 45 03', 43.5530, 1.2645, 'https://www.zoo-africansafari.com/', 'https://www.zoo-africansafari.com/billetterie/', 'https://maps.google.com/?q=African+Safari+Zoo+Plaisance+du+Touch'),
('animaparc_animalier', 'AnimaParc Occitanie', 'Parc animalier', 'Parcs animaliers & fermes autour de Toulouse', 'Parc animalier avec plus de 150 animaux domestiques, activites enfants et attractions thematiques.', 'Lieu-dit En Jacca, 31530 Levignac', 'Mer-Dim 10h-18h (des le 5 avr)', '05 62 79 54 54', 43.6445, 1.1945, 'https://www.animaparc.com/', 'https://www.animaparc.com/billetterie/', 'https://maps.google.com/?q=Animaparc+Levignac'),
('ferme_de_50_animal', 'La Ferme de 50', 'Parc animalier', 'Parcs animaliers & fermes autour de Toulouse', 'Parc animalier et ferme pedagogique avec diverses races domestiques.', 'Lieu-dit Cinquante, 31530 Merenvielle', 'Mer-Dim 10h-18h', '06 80 21 69 50', 43.6310, 1.1615, 'https://www.lafermede50.fr/', '', 'https://maps.google.com/?q=La+Ferme+de+50+Merenvielle'),
('ferme_du_paradis_animal', 'La Ferme du Paradis', 'Parc animalier', 'Parcs animaliers & fermes autour de Toulouse', 'Ferme-parc avec plus d''une centaine d''animaux et aires de jeux gonflables.', 'Lieu-dit Le Paradis, 31370 Rieumes', 'Mer-Dim 10h-18h (saison)', '06 73 19 88 52', 43.4085, 1.1150, 'https://www.lafermeduparadis.fr/', '', 'https://maps.google.com/?q=La+Ferme+du+Paradis+Rieumes'),
('arche_noe_animal', 'L''Arche de Noe de Soly-Ange', 'Parc animalier', 'Parcs animaliers & fermes autour de Toulouse', 'Parc animalier associatif avec une grande variete d''animaux recueillis.', 'Lieu-dit Soly-Ange, 31410 Lavernose-Lacasse', 'Mer-Dim 10h-17h30', '06 16 48 82 93', 43.3930, 1.2680, 'https://www.arche-de-noe-soly-ange.fr/', '', 'https://maps.google.com/?q=Arche+de+Noe+Soly-Ange+Lavernose-Lacasse'),
('zoo_3_vallees', 'Zoo des 3 Vallees', 'Parc animalier', 'Parcs animaliers excursion journee', 'Grand parc zoologique avec environ 600 animaux et 70 especes.', 'Lieu-dit Les Music, 81360 Montredon-Labessonie', 'Avr-Sept 10h-18h', '05 63 75 10 00', 43.7215, 2.3310, 'https://www.zoo3vallees.fr/', 'https://www.zoo3vallees.fr/billetterie/', 'https://maps.google.com/?q=Zoo+des+3+Vallees+Montredon-Labessonie');

-- ═══════════════════════════════════════════════════════
-- Ferme pedagogique (4)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, description, adresse, horaires, telephone, latitude, longitude, website_url, lien_maps) VALUES
('ferme_de_50', 'La Ferme de 50', 'Ferme pedagogique', 'Ferme pedagogique avec diverses races domestiques. Activites pour les enfants, nourrissage des animaux.', 'Lieu-dit Cinquante, 31530 Merenvielle', 'Mer-Dim 10h-18h', '06 80 21 69 50', 43.6310, 1.1615, 'https://www.lafermede50.fr/', 'https://maps.google.com/?q=La+Ferme+de+50+Merenvielle'),
('ferme_du_paradis', 'La Ferme du Paradis', 'Ferme pedagogique', 'Ferme-parc avec plus d''une centaine d''animaux et aires de jeux gonflables pour enfants.', 'Lieu-dit Le Paradis, 31370 Rieumes', 'Mer-Dim 10h-18h (saison)', '06 73 19 88 52', 43.4085, 1.1150, 'https://www.lafermeduparadis.fr/', 'https://maps.google.com/?q=La+Ferme+du+Paradis+Rieumes'),
('arche_noe_soly_ange', 'L''Arche de Noe de Soly-Ange', 'Ferme pedagogique', 'Parc animalier associatif avec une grande variete d''animaux recueillis. Experience intimiste et pedagogique.', 'Lieu-dit Soly-Ange, 31410 Lavernose-Lacasse', 'Mer-Dim 10h-17h30', '06 16 48 82 93', 43.3930, 1.2680, 'https://www.arche-de-noe-soly-ange.fr/', 'https://maps.google.com/?q=Arche+de+Noe+Soly-Ange+Lavernose-Lacasse'),
('ferme_capra_de_pau', 'La Ferme de Capra de Pau', 'Ferme pedagogique', 'Petite ferme pedagogique avec chevres, moutons, poules et anes. Ateliers decouverte pour les enfants.', 'Chemin de Capra de Pau, 31170 Tournefeuille', 'Mer & Sam 14h-17h', '05 61 06 97 41', 43.5830, 1.3490, '', 'https://maps.google.com/?q=Ferme+Capra+de+Pau+Tournefeuille');

-- ═══════════════════════════════════════════════════════
-- Cinema (11)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, groupe, description, adresse, horaires, telephone, latitude, longitude, website_url, ticket_url, lien_maps) VALUES
('pathe_wilson', 'Pathe Wilson', 'Cinema', 'Multiplexes & grands cinemas', 'Grand cinema historique au centre-ville avec nombreuses salles et ecrans modernes.', '3 Place du President Thomas Wilson, 31000 Toulouse', 'Tous les jours 10h-23h', '0892 69 66 96', 43.6075, 1.4480, 'https://www.pathe.fr/cinemas/cinema-pathe-wilson', 'https://www.pathe.fr/cinemas/cinema-pathe-wilson', 'https://maps.google.com/?q=Pathe+Wilson+Place+Wilson+Toulouse'),
('ugc_montaudran', 'UGC Toulouse Montaudran', 'Cinema', 'Multiplexes & grands cinemas', 'Multiplexe avec programmation grand public.', '3 Impasse Michel Labrousse, 31400 Toulouse', 'Tous les jours 10h-23h', '0892 70 00 00', 43.5720, 1.4815, 'https://www.ugc.fr/cinema/ugc-toulouse-montaudran/', 'https://www.ugc.fr/cinema/ugc-toulouse-montaudran/', 'https://maps.google.com/?q=UGC+Toulouse+Montaudran'),
('pathe_labege', 'Pathe Labege', 'Cinema', 'Multiplexes & grands cinemas', 'Grand cinema avec IMAX et grands ecrans dans la zone commerciale de Labege.', 'Centre Commercial Labege 2, 31670 Labege', 'Tous les jours 10h-23h', '0892 69 66 96', 43.5335, 1.5110, 'https://www.pathe.fr/cinemas/cinema-pathe-labege', 'https://www.pathe.fr/cinemas/cinema-pathe-labege', 'https://maps.google.com/?q=Pathe+Labege+Centre+Commercial'),
('american_cosmograph', 'American Cosmograph', 'Cinema', 'Cinemas independants & art', 'Cinema d''art & essai avec programmation eclectique.', '24 Rue Montardy, 31000 Toulouse', 'Tous les jours 13h30-22h30', '05 61 21 22 11', 43.6040, 1.4500, 'https://www.american-cosmograph.fr/', 'https://www.american-cosmograph.fr/horaires/', 'https://maps.google.com/?q=American+Cosmograph+24+Rue+Montardy+Toulouse'),
('cinema_abc', 'ABC', 'Cinema', 'Cinemas independants & art', 'Cinema independant et associatif, soutient le cinema europeen.', '13 Rue Saint-Bernard, 31000 Toulouse', 'Tous les jours 14h-22h', '05 61 21 20 46', 43.6010, 1.4495, 'https://abc-toulouse.fr/', 'https://abc-toulouse.fr/programme/', 'https://maps.google.com/?q=Cinema+ABC+13+Rue+Saint-Bernard+Toulouse'),
('utopia_borderouge', 'Utopia Borderouge', 'Cinema', 'Cinemas independants & art', 'Salle d''art & essai du reseau Utopia.', '59 Avenue Maurice Bourgues-Maunoury, 31200 Toulouse', 'Tous les jours 14h-22h', '05 61 35 26 28', 43.6340, 1.4530, 'https://www.cinemas-utopia.org/toulouse/', 'https://www.cinemas-utopia.org/toulouse/', 'https://maps.google.com/?q=Utopia+Borderouge+Toulouse'),
('le_cratere', 'Le Cratere', 'Cinema', 'Cinemas independants & art', 'Cinema d''art et essai, petite salle conviviale avec programmation originale.', '95 Grande Rue Saint-Michel, 31400 Toulouse', 'Tous les jours 14h-22h', '05 61 53 50 53', 43.5880, 1.4465, 'https://www.cinema-lecratere.com/', 'https://www.cinema-lecratere.com/', 'https://maps.google.com/?q=Le+Cratere+Cinema+Grande+Rue+Saint-Michel+Toulouse'),
('cinematheque_toulouse', 'Cinematheque de Toulouse', 'Cinema', 'Cinemas independants & art', 'Salle et centre d''archives dedies au cinema. En travaux, reouverture prevue 2026.', '69 Rue du Taur, 31000 Toulouse', 'En travaux - reouverture 2026', '05 62 30 30 10', 43.6060, 1.4430, 'https://www.lacinemathequedetoulouse.fr/', '', 'https://maps.google.com/?q=Cinematheque+de+Toulouse+69+Rue+du+Taur'),
('veo_cartoucherie', 'Cinema Veo Cartoucherie', 'Cinema', 'Autres salles interessantes', 'Salle cinema dans le quartier de la Cartoucherie.', 'Allee de la Cartoucherie, 31300 Toulouse', 'Tous les jours 10h-22h30', '05 36 09 09 09', 43.6050, 1.4175, 'https://www.veocinemas.fr/', 'https://www.veocinemas.fr/', 'https://maps.google.com/?q=Cinema+Veo+Cartoucherie+Toulouse'),
('cgr_blagnac', 'Cinema CGR Blagnac', 'Cinema', 'Autres salles interessantes', 'Grand cinema multiplex a Blagnac, pres de Toulouse.', 'Zone de Ritouret, 31700 Blagnac', 'Tous les jours 10h-23h', '0892 68 85 89', 43.6335, 1.3785, 'https://www.cgrcinemas.fr/blagnac/', 'https://www.cgrcinemas.fr/blagnac/', 'https://maps.google.com/?q=CGR+Blagnac'),
('cine_rex_blagnac', 'Cine Rex', 'Cinema', 'Autres salles interessantes', 'Cinema convivial a Blagnac.', '41 Avenue du General de Gaulle, 31700 Blagnac', 'Tous les jours 14h-22h', '05 61 71 42 67', 43.6310, 1.3920, 'https://www.rex-blagnac.fr/', 'https://www.rex-blagnac.fr/', 'https://maps.google.com/?q=Cine+Rex+41+Avenue+General+de+Gaulle+Blagnac');

-- ═══════════════════════════════════════════════════════
-- Bowling (5)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, groupe, description, adresse, horaires, telephone, latitude, longitude, website_url, lien_maps) VALUES
('bowling_gramont', 'Bowling Gramont', 'Bowling', 'Bowls & centres de bowling a Toulouse', 'Centre de bowling majeur avec 26 pistes, bar et restaurant.', '64 Route de Lavaur, 31500 Toulouse', 'Lun-Jeu 14h-00h, Ven-Sam 14h-02h, Dim 10h-00h', '05 61 20 26 26', 43.6285, 1.4885, 'https://www.bowling-gramont.com/', 'https://maps.google.com/?q=Bowling+Gramont+64+Route+de+Lavaur+Toulouse'),
('bowling_montaudran', 'Bowling Montaudran', 'Bowling', 'Bowls & centres de bowling a Toulouse', 'Grand complexe bowling avec jusqu''a 28 pistes, options party.', '1 Impasse Michel Labrousse, 31400 Toulouse', 'Lun-Jeu 14h-00h, Ven-Sam 14h-02h, Dim 10h-00h', '05 61 80 11 22', 43.5725, 1.4810, 'https://www.bowlingmontaudran.fr/', 'https://maps.google.com/?q=Bowling+Montaudran+Impasse+Michel+Labrousse+Toulouse'),
('bowling_center', 'Bowling Center', 'Bowling', 'Bowls & centres de bowling a Toulouse', 'Bowling central a Toulouse avec formules anniversaires et restauration.', '68 Avenue des Minimes, 31200 Toulouse', 'Lun-Jeu 14h-00h, Ven-Sam 14h-02h, Dim 10h-00h', '05 61 47 02 02', 43.6195, 1.4405, 'https://www.bowling-center-toulouse.fr/', 'https://maps.google.com/?q=Bowling+Center+68+Avenue+des+Minimes+Toulouse'),
('games_factory', 'Games Factory - Bowling Toulouse', 'Bowling', 'Bowls & centres de bowling a Toulouse', 'Complexe multi-activites a Roques avec bowling, jeux et formules illimite.', 'Zone Commerciale, 31120 Roques', 'Lun-Jeu 14h-00h, Ven-Sam 14h-02h, Dim 10h-00h', '05 61 72 47 47', 43.5060, 1.3870, 'https://www.gamesfactory.fr/', 'https://maps.google.com/?q=Games+Factory+Bowling+Roques'),
('bowling_stadium_colomiers', 'Bowling Stadium - Colomiers', 'Bowling', 'Autres options proches (agglomeration)', 'Bowling avec 20 pistes, laser game et realite virtuelle.', '2 Allee du Languedoc, 31770 Colomiers', 'Lun-Jeu 14h-00h, Ven-Sam 14h-02h, Dim 10h-00h', '05 61 78 61 61', 43.6030, 1.3365, 'https://www.bowling-stadium.fr/', 'https://maps.google.com/?q=Bowling+Stadium+Colomiers');

-- ═══════════════════════════════════════════════════════
-- Laser game (5)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, description, adresse, horaires, telephone, latitude, longitude, website_url, lien_maps) VALUES
('laser_quest_toulouse', 'Laser Quest', 'Laser game', 'Arene laser game classique avec labyrinthes (~20 min par partie).', '37 Rue Gabriel Bienes, 31300 Toulouse', 'Mer-Dim 14h-22h, Ven-Sam 14h-00h', '05 61 42 04 04', 43.6045, 1.4155, 'https://www.laserquest.fr/toulouse/', 'https://maps.google.com/?q=Laser+Quest+37+Rue+Gabriel+Bienes+Toulouse'),
('laser_trampoline_sept_deniers', 'Laser Game - Trampoline Park Sept Deniers', 'Laser game', 'Laser game integre au Trampoline Park des Sept Deniers.', '120 Route de Blagnac, 31200 Toulouse', 'Mer-Dim 10h-20h, Ven-Sam 10h-22h', '05 61 11 52 52', 43.6175, 1.4230, 'https://www.trampolinepark-toulouse.fr/', 'https://maps.google.com/?q=Trampoline+Park+Sept+Deniers+120+Route+Blagnac+Toulouse'),
('laser_quest_blagnac', 'Laser Quest Toulouse / Blagnac', 'Laser game', 'Laser game dans la commune voisine de Blagnac.', 'Zone Commerciale Ritouret, 31700 Blagnac', 'Mer-Dim 14h-22h, Ven-Sam 14h-00h', '05 61 71 20 20', 43.6340, 1.3780, 'https://www.laserquest.fr/blagnac/', 'https://maps.google.com/?q=Laser+Quest+Blagnac'),
('games_factory_laser', 'Games Factory - Laser Game', 'Laser game', 'Centre de loisirs a Roques avec laser game, bowling et autres activites.', 'Zone Commerciale, 31120 Roques', 'Lun-Jeu 14h-00h, Ven-Sam 14h-02h, Dim 10h-00h', '05 61 72 47 47', 43.5060, 1.3870, 'https://www.gamesfactory.fr/', 'https://maps.google.com/?q=Games+Factory+Roques'),
('laser_game_evolution_portet', 'Laser Game Evolution Portet-sur-Garonne', 'Laser game', 'Arene laser game a Portet-sur-Garonne.', 'Zone Commerciale, 31120 Portet-sur-Garonne', 'Mer-Dim 14h-22h, Ven-Sam 14h-00h', '05 34 47 00 10', 43.5230, 1.4010, 'https://www.lasergame-evolution.com/portet-sur-garonne/', 'https://maps.google.com/?q=Laser+Game+Evolution+Portet-sur-Garonne');

-- ═══════════════════════════════════════════════════════
-- Escape game (16)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, groupe, description, adresse, horaires, telephone, latitude, longitude, website_url, lien_maps) VALUES
('escape_the_game', 'ESCAPE THE GAME - TOULOUSE', 'Escape game', 'Escape games a Toulouse', 'Escape game populaire avec plusieurs aventures immersives en centre-ville.', '27 Rue de la Colombette, 31000 Toulouse', 'Lun-Dim 10h-00h', '05 61 62 49 49', 43.6065, 1.4530, 'https://www.escapethegame.fr/', 'https://maps.google.com/?q=Escape+The+Game+Toulouse+27+Rue+de+la+Colombette'),
('toulousescape', 'Toulousescape', 'Escape game', 'Escape games a Toulouse', 'Escape room au coeur de Toulouse avec plusieurs univers thematiques.', '14 Rue Rivals, 31000 Toulouse', 'Lun-Dim 10h-23h', '06 50 91 29 79', 43.6030, 1.4440, 'https://www.toulousescape.fr/', 'https://maps.google.com/?q=Toulousescape+14+Rue+Rivals+Toulouse'),
('escaperie', 'L''Escaperie', 'Escape game', 'Escape games a Toulouse', 'Escape Game convivial pour groupes, anniversaires ou team building.', '50 Rue du Languedoc, 31000 Toulouse', 'Lun-Dim 10h-23h', '05 61 53 64 64', 43.6005, 1.4475, 'https://www.lescaperie.fr/', 'https://maps.google.com/?q=L+Escaperie+50+Rue+du+Languedoc+Toulouse'),
('get_out', 'Get Out', 'Escape game', 'Escape games a Toulouse', 'Escape game + experiences immersives dans le centre-ville.', '18 Rue Bayard, 31000 Toulouse', 'Lun-Dim 10h-23h30', '05 61 63 72 72', 43.6100, 1.4540, 'https://www.get-out.fr/', 'https://maps.google.com/?q=Get+Out+Escape+Game+18+Rue+Bayard+Toulouse'),
('tactisens', 'Tactisens Escape Game', 'Escape game', 'Escape games a Toulouse', 'Grand escape game polyvalent, souvent ouvert tard.', '32 Rue Raymond IV, 31000 Toulouse', 'Lun-Dim 10h-00h', '05 61 12 31 31', 43.6115, 1.4500, 'https://www.tactisens.com/', 'https://maps.google.com/?q=Tactisens+Escape+Game+32+Rue+Raymond+IV+Toulouse'),
('sphinx_corp', 'SPHINX Corp. Escape Game', 'Escape game', 'Escape games a Toulouse', 'Plusieurs missions disponibles, parfait pour familles et evenements.', '4 Rue Gabriel Peri, 31000 Toulouse', 'Lun-Dim 10h-23h', '05 61 25 00 25', 43.6050, 1.4490, 'https://www.sphinxcorp.fr/', 'https://maps.google.com/?q=Sphinx+Corp+Escape+Game+Toulouse'),
('skryptic', 'Skryptic Escape Game', 'Escape game', 'Escape games a Toulouse', 'Escape game tres bien note avec enigmes variees.', '71 Allee Jean Jaures, 31000 Toulouse', 'Lun-Dim 10h-23h', '05 61 44 00 44', 43.6060, 1.4520, 'https://www.skryptic.com/', 'https://maps.google.com/?q=Skryptic+Escape+Game+71+Allee+Jean+Jaures+Toulouse'),
('mysteria', 'Mysteria Escape', 'Escape game', 'Escape games a Toulouse', 'Escape game avec themes immersifs et ambiance forte.', '6 Rue des Lois, 31000 Toulouse', 'Mar-Dim 10h-22h', '05 61 21 88 88', 43.6040, 1.4430, 'https://www.mysteria-escape.fr/', 'https://maps.google.com/?q=Mysteria+Escape+6+Rue+des+Lois+Toulouse'),
('i_lock_u', 'I Lock U - Escape Game Horreur', 'Escape game', 'Escape games a Toulouse', 'Escape game oriente horreur / sensations fortes.', '25 Rue des Paradoux, 31000 Toulouse', 'Mer-Dim 14h-23h, Ven-Sam 14h-00h', '05 61 23 45 67', 43.6000, 1.4400, 'https://www.ilocku.fr/', 'https://maps.google.com/?q=I+Lock+U+Escape+Game+25+Rue+des+Paradoux+Toulouse'),
('hunting_town', 'Hunting Town Toulouse', 'Escape game', 'Autres types d''escape & jeux d''evasion', 'Escape game outdoor/urbain autour de Toulouse.', 'Centre-ville, 31000 Toulouse', 'Sur reservation', '06 12 34 56 78', 43.6045, 1.4440, 'https://www.huntingtown.fr/', 'https://maps.google.com/?q=Hunting+Town+Toulouse'),
('granhota_games', 'Granhota Games', 'Escape game', 'Autres types d''escape & jeux d''evasion', 'Jeux / escape game en exterieur centres sur le centre historique.', 'Centre historique, 31000 Toulouse', 'Sur reservation', '06 98 76 54 32', 43.6035, 1.4435, 'https://www.granhotagames.fr/', 'https://maps.google.com/?q=Granhota+Games+Toulouse'),
('enigma_bayard', 'Enigma Escape (Rue de Bayard)', 'Escape game', 'Autres escape games proches de Toulouse', 'Complexe tres prise avec plusieurs missions immersives.', '18 Rue de Bayard, 31000 Toulouse', 'Lun-Dim 10h-23h', '05 61 62 00 00', 43.6105, 1.4545, 'https://www.enigma-escape.fr/', 'https://maps.google.com/?q=Enigma+Escape+18+Rue+de+Bayard+Toulouse'),
('enigma_gloire', 'Enigma Escape (Av. de la Gloire)', 'Escape game', 'Autres escape games proches de Toulouse', 'Autre adresse Enigma Escape avec scenarios captivants.', '105 Avenue de la Gloire, 31500 Toulouse', 'Lun-Dim 10h-23h', '05 61 62 00 01', 43.6200, 1.4700, 'https://www.enigma-escape.fr/', 'https://maps.google.com/?q=Enigma+Escape+105+Avenue+de+la+Gloire+Toulouse'),
('enigma_city', 'Enigma City', 'Escape game', 'Autres escape games proches de Toulouse', 'Tres grand escape game interieur inspire d''une ville immersive.', '105 Avenue de la Gloire, 31500 Toulouse', 'Lun-Dim 10h-23h', '05 61 62 00 02', 43.6200, 1.4700, 'https://www.enigmacity.fr/', 'https://maps.google.com/?q=Enigma+City+Toulouse'),
('enigmatic_toulouse', 'ENIGMATIC TOULOUSE', 'Escape game', 'Autres escape games proches de Toulouse', 'Escape game bien note a Labege.', 'Zone commerciale, 31670 Labege', 'Lun-Dim 10h-22h', '05 61 00 11 22', 43.5430, 1.5080, 'https://www.enigmatic-toulouse.fr/', 'https://maps.google.com/?q=Enigmatic+Toulouse+Escape+Game+Labege'),
('tourbillon_ayguesvives', 'Tourbillon Escape Game', 'Escape game', 'Autres escape games proches de Toulouse', 'Escape game immersif a Ayguesvives avec plusieurs themes.', 'Zone Commerciale, 31450 Ayguesvives', 'Mer-Dim 10h-22h', '05 61 81 00 00', 43.4520, 1.5850, 'https://www.tourbillon-escape.fr/', 'https://maps.google.com/?q=Tourbillon+Escape+Game+Ayguesvives');

-- ═══════════════════════════════════════════════════════
-- Patinoire (3)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, description, adresse, horaires, tarif, telephone, latitude, longitude, website_url, lien_maps) VALUES
('patinoire_alex_jany', 'Patinoire Alex Jany', 'Patinoire', 'Plus grande patinoire de Toulouse (60x30m), ouverte toute l''annee sauf juillet. Port des gants obligatoire.', '7 Chemin du Verdon, 31500 Toulouse', 'Mer 16h-18h45, Ven 16h-19h, Sam 15h-19h, Dim 14h30-19h', '2.30-7.15€ (10.65€ avec location patins)', '05 81 91 78 56', 43.63, 1.48, 'https://billetterie.sport.toulouse.fr/tickets/patinoires-3', 'https://maps.google.com/?q=Patinoire+Alex+Jany+7+Chemin+du+Verdon+Toulouse'),
('patinoire_bellevue', 'Patinoire Bellevue', 'Patinoire', 'Petite patinoire conviviale et familiale (30x20m) pres de la faculte Paul Sabatier. Port des gants obligatoire.', '69 ter Route de Narbonne, 31000 Toulouse', 'Lun-Mar-Ven 12h-14h/16h30-18h30, Mer 16h30-18h30, Sam 11h30-16h, Dim 8h30-18h', '3.00-9.70€ (location patins incluse)', '05 61 22 24 80', 43.57, 1.46, 'https://billetterie.sport.toulouse.fr/tickets/patinoires-3', 'https://maps.google.com/?q=Patinoire+Bellevue+69+Route+de+Narbonne+Toulouse'),
('patinoire_blagnac', 'Patinoire Jacques Raynaud - Blagnac', 'Patinoire', 'Grande patinoire municipale de 1800m2 a Blagnac, ideale pour les premieres glisses des enfants. Cafeteria sur place.', '10 Avenue du General de Gaulle, 31700 Blagnac', 'Mer 13h30-17h30, Jeu-Ven 20h30-23h30, Sam 10h30-18h, Dim 10h-18h30', '5€ (4.20€ -12 ans, jardin de glace)', '07 68 45 09 92', 43.6320, 1.3940, 'https://patinoireblagnac.fr/', 'https://maps.google.com/?q=Patinoire+Jacques+Raynaud+Blagnac');

-- ═══════════════════════════════════════════════════════
-- Restaurant familial (5)
-- ═══════════════════════════════════════════════════════
INSERT INTO public.family_venues (slug, name, category, description, adresse, horaires, telephone, latitude, longitude, website_url, lien_maps) VALUES
('air_de_famille', 'L''Air de Famille', 'Restaurant familial', 'Restaurant convivial avec ambiance familiale, parfait pour repas entre parents et enfants.', '24 Rue Pargaminieres, 31000 Toulouse', 'Mar-Sam 12h-14h / 19h-22h', '05 61 21 39 06', 43.6040, 1.4390, 'https://www.lairdefamille-toulouse.fr/', 'https://maps.google.com/?q=L+Air+de+Famille+24+Rue+Pargaminieres+Toulouse'),
('la_belle_famille', 'Restaurant La Belle Famille', 'Restaurant familial', 'Lieu chaleureux et adapte aux familles avec enfants.', '10 Rue des Filatiers, 31000 Toulouse', 'Mar-Sam 12h-14h / 19h-22h30', '05 61 25 61 77', 43.6005, 1.4435, 'https://www.labellefamille-toulouse.fr/', 'https://maps.google.com/?q=La+Belle+Famille+10+Rue+des+Filatiers+Toulouse'),
('chez_cesar', 'Chez Cesar', 'Restaurant familial', 'Buvette situee dans le Jardin des Plantes, tres appreciee des familles.', 'Jardin des Plantes, Allee Frederic Mistral, 31400 Toulouse', 'Mar-Dim 10h-19h (selon saison)', '05 61 52 48 48', 43.5895, 1.4510, 'https://www.chezcesar-toulouse.fr/', 'https://maps.google.com/?q=Chez+Cesar+Jardin+des+Plantes+Toulouse'),
('gigiland', 'Gigiland', 'Restaurant familial', 'Restaurant dans un quartier anime avec une ambiance facile a vivre.', '3 Rue Jules Chalande, 31000 Toulouse', 'Mar-Sam 12h-14h / 19h-22h30', '05 61 22 09 09', 43.6025, 1.4420, 'https://www.gigiland-toulouse.fr/', 'https://maps.google.com/?q=Gigiland+3+Rue+Jules+Chalande+Toulouse'),
('brunch_club', 'Brunch Club', 'Restaurant familial', 'Bonne option pour un brunch en famille ou un repas detendu avec enfants.', '7 Rue de la Bourse, 31000 Toulouse', 'Mer-Dim 9h-16h', '05 61 23 45 00', 43.6035, 1.4455, 'https://www.brunchclub-toulouse.fr/', 'https://maps.google.com/?q=Brunch+Club+7+Rue+de+la+Bourse+Toulouse');
