-- Insert 19 theatre venues into unified venues table
INSERT INTO venues (slug, name, description, mode, category, ville, horaires, website_url, ticket_url, has_online_ticket, photo)
VALUES
  ('cafe_theatre_les_3t', 'Cafe-Theatre Les 3T', 'Cafe-theatre populaire avec pieces, humour et spectacles.', 'culture', 'Theatre', 'Toulouse', 'Tlj 20h-23h', 'https://www.3tcafetheatre.com/', 'https://new.3tcafetheatre.com/reservation/etape-1/', TRUE, 'assets/images/theatre_3t.jpg'),
  ('theatre_de_la_cite', 'TheatredelaCite - CDN Toulouse Occitanie', 'Centre dramatique national, representations variees et programmations saisonnieres.', 'culture', 'Theatre', 'Toulouse', 'Billetterie: Mar-Sam 13h-18h', 'https://theatre-cite.com/', 'https://theatre-cite.com/billetterie/', TRUE, 'assets/images/theatre_cite.jpg'),
  ('sorano_theatre', 'Sorano Theatre', 'Salle de spectacles centree sur la jeune creation.', 'culture', 'Theatre', 'Toulouse', 'Billetterie: Mar-Sam 14h-18h', 'https://theatre-sorano.fr/', 'https://theatre-sorano.fr/billetterie/', TRUE, 'assets/images/theatre_sorano.jpg'),
  ('theatre_garonne', 'Theatre Garonne', 'Scene dediee au theatre contemporain et a la creation.', 'culture', 'Theatre', 'Toulouse', 'Billetterie: Mar-Ven 13h-18h', 'https://www.theatregaronne.com/', 'https://www.theatregaronne.com/information/comment-reserver-et-payer', TRUE, 'assets/images/theatre_garonne.jpg'),
  ('nouveau_theatre_jules_julien', 'Nouveau Theatre Jules-Julien', 'Theatre local avec programmation variee.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', 'https://julesjulien.toulouse.fr/', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('grenier_theatre', 'Grenier Theatre', 'Lieu de spectacles et d''arts vivants.', 'culture', 'Theatre', 'Toulouse', 'Billetterie: Mar-Sam 14h-19h', 'https://www.greniertheatre.org/', 'https://www.billetreduc.com/10232/salle.htm', TRUE, 'assets/images/pochette_theatre.png'),
  ('la_cave_poesie', 'La Cave Poesie', 'Scene alternative melant poesie, arts vivants, petits spectacles et lectures.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', 'https://www.cave-poesie.com/', 'https://billetterie.festik.net/cavepoesie/', TRUE, 'assets/images/theatre_cave_poesie.jpg'),
  ('theatre_du_capitole', 'Theatre du Capitole', 'Opera et theatre lyrique sur la Place du Capitole.', 'culture', 'Theatre', 'Toulouse', 'Billetterie: Lun-Sam 10h-17h30', 'https://opera.toulouse.fr/', 'https://opera.toulouse.fr/acheter-un-billet/', TRUE, 'assets/images/theatre_capitole.jpg'),
  ('theatre_du_grand_rond', 'Theatre du Grand Rond', 'Petit theatre independant dedie a la creation contemporaine.', 'culture', 'Theatre', 'Toulouse', 'Billetterie: Mar-Sam 14h-18h', 'https://www.grand-rond.org/', 'https://www.grand-rond.org/comment-reserver-etou-payer', TRUE, 'assets/images/theatre_grand_rond.jpg'),
  ('theatre_du_pave', 'Theatre du Pave', 'Theatre associatif avec programmation engagee et eclectique.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', 'https://www.theatredupave.org/', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('theatre_le_fil_a_plomb', 'Theatre le Fil a plomb', 'Lieu de creation et de diffusion theatrale.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', 'https://theatrelefilaplomb.fr/', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('theatre_des_mazades', 'Theatre des Mazades', 'Theatre municipal avec programmation familiale et tout public.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', 'https://metropole.toulouse.fr/annuaire/centre-culturel-theatre-des-mazades', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('theatre_du_pont_neuf', 'Theatre du Pont-Neuf', 'Cafe-theatre au coeur du centre historique.', 'culture', 'Theatre', 'Toulouse', 'Tlj 20h-23h', 'https://www.theatredupontneuf.fr/', 'https://www.theatredupontneuf.fr/evenements/reservations/', TRUE, 'assets/images/pochette_theatre.png'),
  ('theatre_de_la_violette', 'Theatre de la Violette', 'Theatre de quartier avec spectacles vivants et humour.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', 'https://www.theatredelaviolette.com/', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('theatre_de_poche', 'Theatre de Poche', 'Petite salle intimiste pour spectacles et one-man-shows.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', '', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('theatre_du_chien_blanc', 'Theatre du Chien Blanc', 'Compagnie et lieu de creation theatrale.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', '', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('cafe_theatre_le_57', 'Cafe-Theatre le 57', 'Cafe-theatre convivial avec humour et spectacles.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', '', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('theatre_de_la_digue', 'Theatre de la Digue', 'Salle de spectacles polyvalente a Saint-Cyprien.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', '', '', FALSE, 'assets/images/pochette_theatre.png'),
  ('theatre_de_la_brique_rouge', 'Theatre de la Brique Rouge', 'Theatre independant avec creation et spectacles vivants.', 'culture', 'Theatre', 'Toulouse', 'Selon programmation', '', '', FALSE, 'assets/images/pochette_theatre.png')
ON CONFLICT (slug, ville) DO NOTHING;
