-- Insert 20 library venues into unified venues table
INSERT INTO venues (slug, name, description, mode, category, groupe, adresse, ville, horaires, services, telephone, latitude, longitude, website_url, lien_maps, photo)
VALUES
  ('mediatheque_jose_cabanis', 'Mediatheque Jose Cabanis', 'Principale mediatheque de la ville, vastes collections adultes, jeunesse, musique et numerique.', 'culture', 'Bibliotheque', 'Mediatheques centrales', '1 Allee Jacques Chaban-Delmas, 31500 Toulouse', 'Toulouse', 'Mar-Sam 10h-19h', 'Pret, Wi-Fi, Espace jeunesse, Espace numerique, Musique, Autoformation', '05 62 27 40 00', 43.6110, 1.4540, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-jose-cabanis/', 'https://maps.google.com/?q=Mediatheque+Jose+Cabanis+1+Allee+Jacques+Chaban-Delmas+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_grand_m', 'Mediatheque Grand M', 'Grande mediatheque de quartier avec animations et ateliers.', 'culture', 'Bibliotheque', 'Mediatheques centrales', '37 Avenue de la Reynerie, 31100 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse, Ateliers, Animations', '05 36 25 20 80', 43.5735, 1.3995, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-grand-m/', 'https://maps.google.com/?q=Mediatheque+Grand+M+37+Avenue+Reynerie+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_empalot', 'Mediatheque Empalot', 'Mediatheque de quartier avec collections variees.', 'culture', 'Bibliotheque', 'Mediatheques centrales', '40 Allee de Bellefontaine, 31400 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse, Animations', '05 62 27 42 52', 43.5830, 1.4420, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-empalot/', 'https://maps.google.com/?q=Mediatheque+Empalot+Allee+Bellefontaine+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_saint_cyprien', 'Mediatheque Saint-Cyprien', 'Une des principales mediatheques de quartier.', 'culture', 'Bibliotheque', 'Mediatheques centrales', 'Place du Ravelin, 31300 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse, Expositions', '05 62 27 42 42', 43.5990, 1.4335, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-saint-cyprien/', 'https://maps.google.com/?q=Mediatheque+Saint-Cyprien+Place+Ravelin+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_minimes', 'Mediatheque des Minimes', 'Collection importante de livres, CD, DVD.', 'culture', 'Bibliotheque', 'Mediatheques centrales', '1 Place du Marche aux Cochons, 31200 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse, CD/DVD', '05 62 27 42 72', 43.6185, 1.4410, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-des-minimes/', 'https://maps.google.com/?q=Mediatheque+des+Minimes+Place+Marche+Cochons+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('biblio_ancely', 'Bibliotheque Ancely', 'Bibliotheque de quartier au coeur du parc de la Maourine.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '1 Chemin des Music, 31300 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 62', 43.6095, 1.4110, 'https://www.bibliotheque.toulouse.fr/bibliotheques/bibliotheque-ancely/', 'https://maps.google.com/?q=Bibliotheque+Ancely+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('biblio_bonnefoy', 'Bibliotheque Bonnefoy', 'Bibliotheque de quartier a Bonnefoy.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '4 Rue du Faubourg Bonnefoy, 31500 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 22', 43.6120, 1.4605, 'https://www.bibliotheque.toulouse.fr/bibliotheques/bibliotheque-bonnefoy/', 'https://maps.google.com/?q=Bibliotheque+Bonnefoy+Faubourg+Bonnefoy+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_cote_pavee', 'Mediatheque Cote Pavee', 'Mediatheque de quartier a la Cote Pavee.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '164 Avenue Jean Rieux, 31500 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 32', 43.5955, 1.4690, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-cote-pavee/', 'https://maps.google.com/?q=Mediatheque+Cote+Pavee+164+Avenue+Jean+Rieux+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_daniele_damin', 'Mediatheque Daniele Damin', 'Mediatheque de quartier au Mirail-Universite.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', 'Impasse Damin, 31100 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 82', 43.5680, 1.4020, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-daniele-damin/', 'https://maps.google.com/?q=Mediatheque+Daniele+Damin+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('biblio_duranti', 'Bibliotheque Duranti', 'Bibliotheque de quartier en centre-ville.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '6 Rue du Perigord, 31000 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 12', 43.6065, 1.4470, 'https://www.bibliotheque.toulouse.fr/bibliotheques/bibliotheque-duranti/', 'https://maps.google.com/?q=Bibliotheque+Duranti+6+Rue+Perigord+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_fabre', 'Mediatheque Fabre', 'Mediatheque de quartier aux Sept-Deniers.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '6 Rue du Lieutenant-Colonel Pelissier, 31200 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 92', 43.6150, 1.4260, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-fabre/', 'https://maps.google.com/?q=Mediatheque+Fabre+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_izards', 'Mediatheque des Izards', 'Mediatheque de quartier aux Izards.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '55 Rue des Izards, 31200 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 76', 43.6250, 1.4395, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-des-izards/', 'https://maps.google.com/?q=Mediatheque+des+Izards+55+Rue+Izards+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('biblio_pavillon_pret', 'Bibliotheque Pavillon de Pret', 'Pavillon de pret de la Bibliotheque de Toulouse.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '2 Rue du Perigord, 31000 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Retour, Wi-Fi', '05 62 27 40 00', 43.6068, 1.4465, 'https://www.bibliotheque.toulouse.fr/bibliotheques/pavillon-de-pret/', 'https://maps.google.com/?q=Pavillon+de+Pret+Bibliotheque+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('biblio_pinel', 'Bibliotheque Pinel', 'Bibliotheque de quartier a Lardenne.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '84 Chemin de Lardenne, 31100 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 86', 43.5920, 1.3935, 'https://www.bibliotheque.toulouse.fr/bibliotheques/bibliotheque-pinel/', 'https://maps.google.com/?q=Bibliotheque+Pinel+Chemin+Lardenne+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('biblio_pont_demoiselles', 'Bibliotheque Pont des Demoiselles', 'Bibliotheque de quartier pres du canal.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '1 Allees des Demoiselles, 31400 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 46', 43.5935, 1.4560, 'https://www.bibliotheque.toulouse.fr/bibliotheques/bibliotheque-pont-des-demoiselles/', 'https://maps.google.com/?q=Bibliotheque+Pont+des+Demoiselles+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_pradettes', 'Mediatheque des Pradettes', 'Mediatheque de quartier aux Pradettes.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '2 Rue Marie-Rose Gineste, 31100 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 96', 43.5865, 1.3870, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-des-pradettes/', 'https://maps.google.com/?q=Mediatheque+des+Pradettes+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_rangueil', 'Mediatheque Rangueil', 'Mediatheque de quartier a Rangueil.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '21 Avenue de Rangueil, 31400 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 56', 43.5780, 1.4535, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-rangueil/', 'https://maps.google.com/?q=Mediatheque+Rangueil+21+Avenue+Rangueil+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('biblio_roseraie', 'Bibliotheque Roseraie', 'Bibliotheque de quartier a la Roseraie.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '7 Place Duc. d''Aubuisson, 31500 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 36', 43.6015, 1.4715, 'https://www.bibliotheque.toulouse.fr/bibliotheques/bibliotheque-roseraie/', 'https://maps.google.com/?q=Bibliotheque+Roseraie+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_saint_exupery', 'Mediatheque Saint-Exupery', 'Mediatheque de quartier a Bagatelle.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '1 Allee Saint-Exupery, 31100 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 66', 43.5825, 1.4145, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-saint-exupery/', 'https://maps.google.com/?q=Mediatheque+Saint-Exupery+Bagatelle+Toulouse', 'assets/images/pochette_culture_art.png'),
  ('mediatheque_serveyrolles', 'Mediatheque Serveyrolles', 'Mediatheque de quartier a Soupetard.', 'culture', 'Bibliotheque', 'Bibliotheques de quartier', '10 Rue Jean-Baptiste Lully, 31500 Toulouse', 'Toulouse', 'Mar-Sam 10h-18h', 'Pret, Wi-Fi, Espace jeunesse', '05 62 27 42 26', 43.6035, 1.4750, 'https://www.bibliotheque.toulouse.fr/bibliotheques/mediatheque-serveyrolles/', 'https://maps.google.com/?q=Mediatheque+Serveyrolles+Soupetard+Toulouse', 'assets/images/pochette_culture_art.png')
ON CONFLICT (slug, ville) DO NOTHING;
