-- Insert 19 monument venues into unified venues table
INSERT INTO venues (slug, name, description, mode, category, groupe, type, adresse, ville, latitude, longitude, website_url, lien_maps, photo)
VALUES
  ('hotel_assezat', 'Hotel d''Assezat', 'Magnifique hotel particulier Renaissance, musee et fondation Bemberg.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', 'Place d''Assezat, 31000 Toulouse', 'Toulouse', 43.6000, 1.4410, 'https://fr.wikipedia.org/wiki/H%C3%B4tel_d%27Ass%C3%A9zat', 'https://maps.google.com/?q=Hotel+d+Assezat+Toulouse', 'assets/images/monument_hotel_assezat.jpg'),
  ('hotel_dumay', 'Hotel Dumay', 'Hotel Renaissance abritant le Musee du Vieux Toulouse.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', '7 Rue du May, 31000 Toulouse', 'Toulouse', 43.6025, 1.4440, 'https://fr.wikipedia.org/wiki/H%C3%B4tel_Dumay', 'https://maps.google.com/?q=Hotel+Dumay+7+Rue+du+May+Toulouse', 'assets/images/monument_hotel_dumay.jpg'),
  ('hotel_dahus', 'Hotel Dahus (Hotel de Tournoer)', 'Ancien hotel du capitoul Pierre Dahus.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', '9 Rue Ozenne, 31000 Toulouse', 'Toulouse', 43.5985, 1.4480, 'https://fr.wikipedia.org/wiki/H%C3%B4tel_Dahus', 'https://maps.google.com/?q=Hotel+Dahus+9+Rue+Ozenne+Toulouse', 'assets/images/monument_hotel_dahus.jpg'),
  ('hotel_ulmo', 'Hotel d''Ulmo (Jean de Ulmo)', 'Hotel Renaissance du XVIe siecle.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', '15 Rue Ninau, 31000 Toulouse', 'Toulouse', 43.5980, 1.4445, 'https://fr.wikipedia.org/wiki/H%C3%B4tel_d%27Ulmo', 'https://maps.google.com/?q=Hotel+d+Ulmo+15+Rue+Ninau+Toulouse', 'assets/images/monument_hotel_ulmo.jpg'),
  ('hotel_bagis', 'Hotel de Bagis (Hotel de Pierre)', 'Remarquable pour sa facade entierement en pierre.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', '25 Rue de la Dalbade, 31000 Toulouse', 'Toulouse', 43.5990, 1.4425, 'https://fr.wikipedia.org/wiki/H%C3%B4tel_de_Pierre_(Toulouse)', 'https://maps.google.com/?q=Hotel+de+Pierre+25+Rue+de+la+Dalbade+Toulouse', 'assets/images/monument_hotel_bagis.jpg'),
  ('hotel_calespoutrat', 'Hotel particulier Calespoutrat', 'Hotel historique toulousain inscrit au patrimoine.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', 'Rue des Changes, 31000 Toulouse', 'Toulouse', 43.6030, 1.4435, 'https://www.pop.culture.gouv.fr/recherche/merimee?mainSearch=Calespoutrat%20Toulouse', 'https://maps.google.com/?q=Hotel+Calespoutrat+Rue+des+Changes+Toulouse', 'assets/images/pochette_visite.png'),
  ('hotel_jean_catel', 'Hotel Jean Catel', 'Facades et toitures historiques inscrites.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', '1 Rue de la Dalbade, 31000 Toulouse', 'Toulouse', 43.5995, 1.4430, 'https://fr.wikipedia.org/wiki/H%C3%B4tel_de_Jean_Catel', 'https://maps.google.com/?q=Hotel+Jean+Catel+Rue+de+la+Dalbade+Toulouse', 'assets/images/monument_hotel_jean_catel.jpg'),
  ('hotel_la_fage', 'Hotel de la Fage (de Lafage)', 'Immeuble remarquable place Saint-Georges.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', 'Place Saint-Georges, 31000 Toulouse', 'Toulouse', 43.6005, 1.4490, 'https://www.pop.culture.gouv.fr/recherche/merimee?mainSearch=Lafage%20Toulouse', 'https://maps.google.com/?q=Hotel+de+Lafage+Place+Saint-Georges+Toulouse', 'assets/images/monument_hotel_la_fage.jpg'),
  ('hotel_gayssion', 'Hotel de Gayssion', 'Hotel historique du coeur de ville.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', 'Rue Croix-Baragnon, 31000 Toulouse', 'Toulouse', 43.5998, 1.4475, 'https://fr.wikipedia.org/wiki/H%C3%B4tel_de_Gayssion', 'https://maps.google.com/?q=Hotel+de+Gayssion+Rue+Croix-Baragnon+Toulouse', 'assets/images/monument_hotel_gayssion.jpg'),
  ('hopital_larrey', 'Ancien hopital Larrey', 'Ancien etablissement hospitalier historique de la ville.', 'culture', 'Monument historique', 'Hotels particuliers', 'Hotel particulier', 'Place Lange, 31000 Toulouse', 'Toulouse', 43.6030, 1.4415, 'https://fr.wikipedia.org/wiki/H%C3%B4pital_Larrey_(Toulouse)', 'https://maps.google.com/?q=Ancien+Hopital+Larrey+Place+Lange+Toulouse', 'assets/images/monument_hopital_larrey.jpg'),
  ('rempart_medieval', 'Vestiges du Rempart medieval', 'Traces de l''enceinte historique de Toulouse.', 'culture', 'Monument historique', 'Urbanisme & vestiges historiques', 'Vestige', 'Place du Salin, 31000 Toulouse', 'Toulouse', 43.5975, 1.4490, 'https://fr.wikipedia.org/wiki/Remparts_de_Toulouse', 'https://maps.google.com/?q=Rempart+medieval+Place+du+Salin+Toulouse', 'assets/images/monument_rempart_medieval.jpg'),
  ('remparts_saint_cyprien', 'Anciens remparts Saint-Cyprien', 'Vestiges inscrits au patrimoine.', 'culture', 'Monument historique', 'Urbanisme & vestiges historiques', 'Vestige', 'Quartier Saint-Cyprien, 31300 Toulouse', 'Toulouse', 43.5990, 1.4320, 'https://fr.wikipedia.org/wiki/Remparts_de_Toulouse', 'https://maps.google.com/?q=Remparts+Saint-Cyprien+Toulouse', 'assets/images/monument_remparts_saint_cyprien.jpg'),
  ('anciens_abattoirs', 'Anciens Abattoirs', 'Batiments historiques rehabilites en musee d''art contemporain.', 'culture', 'Monument historique', 'Urbanisme & vestiges historiques', 'Vestige', '76 Allees Charles de Fitte, 31300 Toulouse', 'Toulouse', 43.6010, 1.4310, 'https://fr.wikipedia.org/wiki/Les_Abattoirs', 'https://maps.google.com/?q=Les+Abattoirs+76+Allees+Charles+de+Fitte+Toulouse', 'assets/images/monument_anciens_abattoirs.jpg'),
  ('pont_touch', 'Pont sur le Touch', 'Ouvrage inscrit au patrimoine.', 'culture', 'Monument historique', 'Urbanisme & vestiges historiques', 'Pont', 'Pont sur le Touch, 31000 Toulouse', 'Toulouse', 43.5965, 1.3985, 'https://www.pop.culture.gouv.fr/recherche/merimee?mainSearch=Pont%20Touch%20Toulouse', 'https://maps.google.com/?q=Pont+sur+le+Touch+Toulouse', 'assets/images/monument_pont_touch.jpg'),
  ('ecluse_saint_pierre', 'Ecluse Double Saint-Pierre', 'Ouvrage hydraulique a valeur patrimoniale sur le Canal de Brienne.', 'culture', 'Monument historique', 'Urbanisme & vestiges historiques', 'Ouvrage hydraulique', 'Canal de Brienne, 31000 Toulouse', 'Toulouse', 43.6085, 1.4340, 'https://fr.wikipedia.org/wiki/Canal_de_Brienne', 'https://maps.google.com/?q=Ecluse+Saint-Pierre+Canal+de+Brienne+Toulouse', 'assets/images/monument_ecluse_saint_pierre.jpg'),
  ('eglise_saint_pierre_cuisines', 'Ancienne Eglise Saint-Pierre-des-Cuisines', 'Vestige religieux protege, aujourd''hui auditorium.', 'culture', 'Monument historique', 'Autres elements inscrits', 'Edifice religieux', 'Place Saint-Pierre, 31000 Toulouse', 'Toulouse', 43.6045, 1.4365, 'https://fr.wikipedia.org/wiki/%C3%89glise_Saint-Pierre-des-Cuisines_de_Toulouse', 'https://maps.google.com/?q=Eglise+Saint-Pierre-des-Cuisines+Place+Saint-Pierre+Toulouse', 'assets/images/monument_eglise_saint_pierre_cuisines.jpg'),
  ('college_jesuites', 'Ancien College des Jesuites', 'Batiments historiques, aujourd''hui lycee Pierre-de-Fermat.', 'culture', 'Monument historique', 'Autres elements inscrits', 'Edifice religieux', 'Rue Lakanal, 31000 Toulouse', 'Toulouse', 43.6025, 1.4440, 'https://fr.wikipedia.org/wiki/Lyc%C3%A9e_Pierre-de-Fermat', 'https://maps.google.com/?q=College+des+Jesuites+Rue+Lakanal+Toulouse', 'assets/images/monument_college_jesuites.jpg'),
  ('couvent_cordeliers', 'Ancien Couvent des Cordeliers', 'Vestiges gallo-romains et medievaux.', 'culture', 'Monument historique', 'Autres elements inscrits', 'Edifice religieux', 'Rue des Lois, 31000 Toulouse', 'Toulouse', 43.5985, 1.4445, 'https://fr.wikipedia.org/wiki/Couvent_des_Cordeliers_de_Toulouse', 'https://maps.google.com/?q=Couvent+des+Cordeliers+Rue+des+Lois+Toulouse', 'assets/images/monument_couvent_cordeliers.jpg'),
  ('maison_guignard', 'Maison Guignard', 'Immeuble ancien protege au patrimoine.', 'culture', 'Monument historique', 'Autres elements inscrits', 'Immeuble', 'Centre historique, 31000 Toulouse', 'Toulouse', 43.6010, 1.4450, 'https://www.pop.culture.gouv.fr/recherche/merimee?mainSearch=Guignard%20Toulouse', 'https://maps.google.com/?q=Maison+Guignard+Toulouse', 'assets/images/monument_maison_guignard.jpg')
ON CONFLICT (slug, ville) DO NOTHING;
