-- Cron jobs pour scrape-spectacles multi-villes
-- Reparties entre 3h30 et 3h55 UTC

SELECT cron.schedule('scrape-spectacles-lyon', '30 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lyon"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-marseille', '32 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Marseille"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-bordeaux', '34 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Bordeaux"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-lille', '36 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lille"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-nantes', '38 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nantes"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-toulouse-eb', '40 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Toulouse"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-nice', '42 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nice"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-strasbourg', '44 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Strasbourg"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-rennes', '46 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Rennes"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-montpellier', '48 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Montpellier"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-grenoble', '50 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Grenoble"}'::jsonb);$$);
SELECT cron.schedule('scrape-spectacles-paris-eb', '52 3 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-spectacles',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Paris"}'::jsonb);$$);
