-- Cron jobs pour scrape-famille multi-villes
-- Reparties entre 1h00 et 1h30 UTC

SELECT cron.schedule('scrape-famille-paris', '0 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Paris"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-lyon', '3 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lyon"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-marseille', '6 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Marseille"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-bordeaux', '9 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Bordeaux"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-lille', '12 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Lille"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-nantes', '15 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nantes"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-toulouse', '18 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Toulouse"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-nice', '21 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Nice"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-strasbourg', '24 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Strasbourg"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-rennes', '27 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Rennes"}'::jsonb);$$);
SELECT cron.schedule('scrape-famille-montpellier', '30 1 * * *', $$SELECT net.http_post(url:='https://dpqxefmwjfvoysacwgef.supabase.co/functions/v1/scrape-famille',headers:=jsonb_build_object('Authorization','Bearer '||current_setting('app.settings.service_role_key',true),'Content-Type','application/json'),body:='{"ville":"Montpellier"}'::jsonb);$$);
