-- Insert 17 museum venues into unified venues table
INSERT INTO venues (slug, name, description, mode, category, groupe, ville, horaires, website_url, ticket_url, has_online_ticket, photo)
VALUES
  ('musee_des_augustins', 'Musee des Augustins', 'Musee des beaux-arts avec peintures et sculptures du Moyen Age a aujourd''hui.', 'culture', 'Musee', 'art', 'Toulouse', 'Mar-Dim 10h-18h', 'https://www.augustins.org/', 'https://www.augustins.org/billetterie', TRUE, 'assets/images/augustin_musee.png'),
  ('les_abattoirs', 'Les Abattoirs', 'Musee d''art moderne et contemporain.', 'culture', 'Musee', 'art', 'Toulouse', 'Mar-Dim 12h-18h', 'https://www.lesabattoirs.org/', 'https://www.lesabattoirs.org/billetterie', TRUE, 'assets/images/abbatoirs_musee.png'),
  ('fondation_bemberg', 'Fondation Bemberg - Hotel d''Assezat', 'Collections d''art europeen (peinture, sculpture).', 'culture', 'Musee', 'art', 'Toulouse', 'Mar-Dim 10h-12h30 / 13h30-18h', 'https://www.fondation-bemberg.fr/', 'https://www.fondation-bemberg.fr/billetterie/', TRUE, 'assets/images/fondationbemberg_musee.png'),
  ('musee_paul_dupuy', 'Musee Paul-Dupuy', 'Arts decoratifs, arts graphiques et histoire locale.', 'culture', 'Musee', 'art', 'Toulouse', 'Mar-Dim 10h-17h', 'https://www.musees-toulouse.fr/musee-paul-dupuy', '', FALSE, 'assets/images/pauldupuy_musee.png'),
  ('musee_saint_raymond', 'Musee Saint-Raymond', 'Musee archeologique avec collections antiques.', 'culture', 'Musee', 'histoire', 'Toulouse', 'Mar-Dim 10h-18h', 'https://saintraymond.toulouse.fr/', '', FALSE, 'assets/images/saintraymond_musee.png'),
  ('musee_du_vieux_toulouse', 'Musee du Vieux Toulouse', 'Histoire de la ville.', 'culture', 'Musee', 'histoire', 'Toulouse', 'Lun-Ven 14h-17h', 'https://www.museeduvieux-toulouse.fr/', '', FALSE, 'assets/images/vieuxtoulouse_musee.png'),
  ('musee_histoire_medecine', 'Musee de l''Histoire de la Medecine', 'Instruments et histoire de la medecine a Toulouse.', 'culture', 'Musee', 'science', 'Toulouse', 'Lun-Ven 11h-16h', 'https://www.univ-tlse3.fr/musee-d-histoire-de-la-medecine', '', FALSE, 'assets/images/histoiredelamedecine_musee.png'),
  ('musee_resistance_deportation', 'Musee de la Resistance & de la Deportation', 'Memoire de la Seconde Guerre mondiale.', 'culture', 'Musee', 'histoire', 'Toulouse', 'Mar-Ven 10h-17h', 'https://musee-resistance.haute-garonne.fr/', '', FALSE, 'assets/images/museedelaresistance_musee.png'),
  ('musee_georges_labit', 'Musee Georges Labit', 'Collections d''arts d''Asie et d''Egypte.', 'culture', 'Musee', 'culture', 'Toulouse', 'Mar-Dim 10h-17h', 'https://www.musees-toulouse.fr/musee-georges-labit', '', FALSE, 'assets/images/georgeslabit_musee.png'),
  ('museum_de_toulouse', 'Museum de Toulouse', 'Museum d''histoire naturelle (faune, flore, geologie).', 'culture', 'Musee', 'science', 'Toulouse', 'Mar-Dim 10h-18h', 'https://www.museum.toulouse.fr/', 'https://www.museum.toulouse.fr/billetterie', TRUE, 'assets/images/museum_musee.png'),
  ('jardins_du_museum', 'Les Jardins du Museum', 'Extension nature / jardins du Museum.', 'culture', 'Musee', 'science', 'Toulouse', 'Mar-Dim 10h-18h', 'https://www.museum.toulouse.fr/les-jardins-du-museum', '', FALSE, 'assets/images/jardindumuseum_musee.png'),
  ('cite_de_l_espace', 'Cite de l''Espace', 'Parc/science dedie a l''espace et a l''astronomie.', 'culture', 'Musee', 'science', 'Toulouse', 'Tlj 10h-17h / 10h-19h (ete)', 'https://www.cite-espace.com/', 'https://www.cite-espace.com/billetterie/', TRUE, 'assets/images/citeespace_museum.png'),
  ('musee_aeroscopia', 'Musee Aeroscopia', 'Aviation et histoire aeronautique.', 'culture', 'Musee', 'science', 'Blagnac', 'Tlj 10h-18h', 'https://www.musee-aeroscopia.fr/', 'https://www.musee-aeroscopia.fr/billetterie', TRUE, 'assets/images/aeroscopia_musee.png'),
  ('envol_des_pionniers', 'L''Envol des Pionniers', 'Musee dedie a l''aeropostale et aux pionniers de l''aviation.', 'culture', 'Musee', 'histoire', 'Toulouse', 'Mar-Dim 10h-18h', 'https://www.lenvol-des-pionniers.com/', 'https://www.lenvol-des-pionniers.com/billetterie/', TRUE, 'assets/images/envoldespionniers_musee.png'),
  ('halle_de_la_machine', 'Halle de la Machine', 'Creations mecaniques geantes et installations interactives.', 'culture', 'Musee', 'culture', 'Toulouse', 'Mar-Dim 10h30-17h30', 'https://www.halledelamachine.fr/', 'https://www.halledelamachine.fr/billetterie/', TRUE, 'assets/images/halledelamachine_musee.png'),
  ('espace_patrimoine_toulouse', 'Espace Patrimoine', 'Petit espace d''exposition dedie au patrimoine local.', 'culture', 'Musee', 'culture', 'Toulouse', 'Mar-Sam 10h-18h', 'https://www.toulouse.fr/web/patrimoine', '', FALSE, 'assets/images/espacepatrimoine_musee.png'),
  ('galerie_chateau_d_eau', 'Galerie Le Chateau d''Eau', 'Galerie et lieu museal dedie a la photographie.', 'culture', 'Musee', 'art', 'Toulouse', 'Mar-Dim 13h-19h', 'https://www.galeriechateaudeau.org/', '', FALSE, 'assets/images/chateaudeau_musee.png')
ON CONFLICT (slug, ville) DO NOTHING;
